<?php

declare(strict_types=1);

namespace DataKit\DataViews\Query\Backend\WordPress;

use DataKit\DataViews\Query\AggregateField;
use DataKit\DataViews\Query\AggregateFunction;
use DataKit\DataViews\Query\Exception\QueryValidationException;

/**
 * Compiles AggregateFunction enums to MySQL aggregate expressions.
 *
 * Shared across all WordPress SQL backends.
 *
 * @internal $colExpr is always generated by the backend's own buildColumnMap(),
 *           never from user input. It is safe to interpolate directly.
 *
 * @since $ver$
 */
final class SqlAggregateCompiler
{
    /**
     * Compile an aggregate field to a MySQL SELECT expression.
     *
     * @param AggregateField $metric  The aggregate field.
     * @param string|null    $colExpr The SQL column expression (null for COUNT(*)).
     *
     * @return string The MySQL SELECT expression with alias.
     */
    public function compile(AggregateField $metric, ?string $colExpr): string
    {
        // SUM, AVG, MIN, MAX require a column expression.
        // A null/empty colExpr with these functions produces invalid SQL like "SUM()".
        if (($colExpr === null || $colExpr === '') && !in_array($metric->function, [AggregateFunction::Count, AggregateFunction::CountDistinct], true)) {
            throw QueryValidationException::invalidValue(
                $metric->outputName(),
                sprintf('%s() requires a field — wildcard (*) is only valid with COUNT.', $metric->function->value),
            );
        }

        $expr = match ($metric->function) {
            AggregateFunction::Count => $colExpr !== null && $colExpr !== '' ? "COUNT({$colExpr})" : 'COUNT(*)',
            AggregateFunction::CountDistinct => $colExpr !== null && $colExpr !== '' ? "COUNT(DISTINCT {$colExpr})" : 'COUNT(*)',
            AggregateFunction::Sum => "SUM({$colExpr})",
            AggregateFunction::Avg => "AVG({$colExpr})",
            AggregateFunction::Min => "MIN({$colExpr})",
            AggregateFunction::Max => "MAX({$colExpr})",
        };

        $alias = str_replace('`', '``', $metric->outputName());

        return "{$expr} AS `{$alias}`";
    }
}
